name: Setup Starknet Foundry
description: Sets up Starknet Foundry in your GitHub Actions workflow
author: Foundry
branding:
  color: blue
  icon: activity
inputs:
  starknet-foundry-version:
    description: Starknet Foundry version to use
    required: false
outputs:
  starknet-foundry-prefix:
    description: The prefix of installed Starknet Foundry
  starknet-foundry-version:
    description: The version of installed Starknet Foundry
runs:
  using: node20
  main: "dist/index.js"
