name: Setup Starknet Foundry
description: Sets up Starknet Foundry in your GitHub Actions workflow
author: Foundry
branding:
  color: blue
  icon: activity
inputs:
  starknet-foundry-version:
    description: Starknet Foundry version to use
    required: false
  tool-versions:
    description: Path to .tool-versions file
    required: false
outputs:
  starknet-foundry-prefix:
    description: The prefix of installed Starknet Foundry
  starknet-foundry-version:
    description: The version of installed Starknet Foundry
runs:
  using: "composite"
  steps:
    - name: Set up Universal Sierra Compiler
      uses: software-mansion/setup-universal-sierra-compiler@v1

    - name: Set up Starknet Foundry
      shell: bash
      run: node $GITHUB_ACTION_PATH/dist/index.js
